services:
  reid-tracker:
    image: main-algoritm
    container_name: main-algoritm-container
    build:
      context: .
      dockerfile: Dockerfile
    command: ['python', 'reindetification.py']
    volumes:
      - ./reindetification.py:/app/reindetification.py
      - ./config/camera.py:/app/config/camera.py
      - ./videos/arch_7am_no.mp4:/app/videos/arch_7am_no.mp4

